matrix:
  include:
    - language: java
      jdk: oraclejdk11
      install:
        - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      before_install:
        - cd ./restful-web-services
        - openssl aes-256-cbc -K $encrypted_5c9ac4a7e4ce_key -iv $encrypted_5c9ac4a7e4ce_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d

    - language: node_js
      node_js: stable
      install:
        - npm install
      before_install:
        - cd ./frontend/social-app
      script:
        - npm run
